/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2a2a2a",
        "on-error": "#690005",
        "tertiary-container": "#000000",
        "on-tertiary-fixed-variant": "#2a4386",
        "on-primary": "#303030",
        secondary: "#c6c6c7",
        "surface-tint": "#c6c6c6",
        background: "#131313",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#353535",
        error: "#ffb4ab",
        "primary-fixed": "#e2e2e2",
        "surface-bright": "#393939",
        "surface-container-low": "#1b1b1b",
        "surface-dim": "#131313",
        "inverse-primary": "#5e5e5e",
        "inverse-surface": "#e2e2e2",
        "on-primary-fixed": "#1b1b1b",
        "on-secondary-container": "#b4b5b5",
        "secondary-fixed": "#e2e2e2",
        "secondary-container": "#454747",
        "on-background": "#e2e2e2",
        "tertiary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#b3c5ff",
        "on-secondary-fixed": "#1a1c1c",
        "primary-container": "#000000",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#e2e2e2",
        outline: "#988e90",
        "on-secondary": "#2f3131",
        "on-tertiary-container": "#5b73b8",
        "on-primary-container": "#757575",
        "surface-variant": "#353535",
        tertiary: "#b3c5ff",
        "error-container": "#93000a",
        "primary-fixed-dim": "#c6c6c6",
        "on-tertiary": "#0d2c6e",
        "on-tertiary-fixed": "#00174a",
        surface: "#131313",
        "inverse-on-surface": "#303030",
        "outline-variant": "#4c4546",
        "on-secondary-fixed-variant": "#454747",
        "on-primary-fixed-variant": "#474747",
        "on-surface-variant": "#cfc4c5",
        primary: "#c6c6c6",
        "surface-container": "#1f1f1f",
        "secondary-fixed-dim": "#c6c6c7",
        "royal-blue": "#2a4386",
        "accent-yellow": "#F7FF00",
        "neon-purple-start": "#B026FF",
        "neon-purple-end": "#6F00FF",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "unit-lg": "32px",
        "container-max": "1440px",
        "unit-xs": "4px",
        "sidebar-width": "80px",
        "unit-md": "16px",
        gutter: "24px",
        "unit-xl": "64px",
        "unit-sm": "8px",
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Sora", "sans-serif"],
        "headline-lg-mobile": ["Sora", "sans-serif"],
        "display-jw": ["Sora", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-mono": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" },
        ],
        "headline-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "40px", fontWeight: "700" },
        ],
        "display-jw": [
          "120px",
          {
            lineHeight: "110px",
            letterSpacing: "-0.04em",
            fontWeight: "800",
          },
        ],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
